name: setup-dev-env
description: "Setup development environment"

inputs:
  python-version:
    default: "3.7"

runs:
  using: composite

  steps:
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Upgrade or install system packages
      shell: bash
      run: python -m pip install --upgrade pip wheel appdirs

    - name: appdir
      shell: bash
      run:
        echo $(python -c "import appdirs; print(appdirs.user_cache_dir('pip',
        app_author=False))")

    - name: Get pip cache path
      id: get-cache-path
      shell: bash
      env:
        OS: ${{ runner.os }}
      run: >
        echo "::set-output name=path::$(
          python .github/actions/setup-dev-env/get_cache_path.py
        )"

    - name: Restore pip cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.get-cache-path.outputs.path }}
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements-dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup development environment
      shell: bash
      run: |
        pip install doit
        doit setup
