name: setup-dev-env
description: "Setup development environment"

inputs:
  python-version:
    default: "3.9"

runs:
  using: composite

  steps:
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Get pip cache path
      id: get-cache-path
      shell: bash
      run: |
        pip install appdirs
        CACHE_PATH=`python -c "import appdirs; print(appdirs.user_cache_dir('pip', appauthor=False))"`
        echo "path=${CACHE_PATH}" >> $GITHUB_OUTPUT

    - name: Restore pip cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.get-cache-path.outputs.path }}
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements-dev.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Upgrade or install system packages
      shell: bash
      run: python -m pip install --upgrade pip wheel

    - name: Install development requirements and project
      shell: bash
      run: |
        pip install doit tomlkit
        doit install
