name: setup-dev-env
description: "Setup development environment"

inputs:
   python-version:
     default: "3.7"

runs:
  using: composite
  steps:
    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}

    - name: Upgrade pip
      shell: bash
      run: python -m pip install --upgrade pip

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install development packages
      shell: bash
      run: pip install -r requirements-dev.txt

    - name: Install light-the-torch
      shell: bash
      run: pip install -e .
