name: install

on:
  push:
    branches:
      - main
      - releases/*

  pull_request:

jobs:
  torch_cpu:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
        pytorch-channel:
          - stable
          - test
          - nightly
          - lts
        exclude:
          - os: macos-latest
            pytorch-channel: lts
          - python-version: "3.10"
            pytorch-channel: lts
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup development environment
        uses: ./.github/actions/setup-dev-env
        with:
          python-version: ${{ matrix.python-version }}

      - name: Collect environment information
        run: python scripts/collect_env.py

      - name: Install torch
        run: ltt install --cpuonly --pytorch-channel=${{ matrix.pytorch-channel }} torch

      - name: Check if CPU only
        shell: python
        run: |
          import sys
          import torch

          compiled_with_cuda = hasattr(torch._C, "_cuda_getDeviceCount")
          sys.exit(compiled_with_cuda)
