name: install

on:
  push:
    branches:
      - main
      - releases/*

  pull_request:

jobs:
  torch_cpu:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
        pytorch-channel:
          - ""
          - stable
          - test
          - nightly
          - lts
        exclude:
          - os: macos-latest
            pytorch-channel: lts
          - python-version: "3.10"
            pytorch-channel: lts
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup development environment
        uses: ./.github/actions/setup-dev-env
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install torch
        env:
          CHANNEL: ${{ matrix.pytorch-channel }}
        run: ltt install --cpuonly ${CHANNEL:+--pytorch-channel=$CHANNEL} torch

      - name: Check if CPU only
        run:
          python -c "import sys, torch; sys.exit(hasattr(torch._C,
          '_cuda_getDeviceCount'))"
