name: publishable

on:
  push:
    branches:
      - master
      - releases/*

  pull_request:
    paths:
      - ".github/workflows/publishable.yml"
      - "light_the_torch/**"
      - ".gitignore"
      - "CONTRIBUTING.rst"
      - "dodo.py"
      - "LICENSE"
      - "MANIFEST.in"
      - "pyproject.toml"
      - "README.rst"
      - "requirements-dev.txt"
      - "setup.cfg"

jobs:
  pypi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: ./.github/actions/setup-dev-env

      - name: Check if publishable
        run: doit publishable
